Models/Contacto.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CrudASP.Models
{
    public class Contacto
    {
        //==============================================================================
        [Key]
        public int Id { get; set; }
        //==============================================================================

        //==============================================================================
        [Required(ErrorMessage ="El nombre es Obligatorio")]
        [StringLength(50)]
        public string Nombre { get; set; }
        //==============================================================================

        //==============================================================================
        [Phone]
        [Required(ErrorMessage = "El telefono es Obligatorio")]
        [Display(Name = "Teléfono")]
        [StringLength(8)]
        public string Telefono { get; set; }
        //==============================================================================

        //==============================================================================
        [Phone]
        [Required(ErrorMessage = "El celular es Obligatorio")]
        [Display(Name = "Celular")]
        [StringLength(8)]
        public string Celular { get; set; }
        //==============================================================================

        //==============================================================================
        [EmailAddress]
        [Required(ErrorMessage = "El email es Obligatorio")]
        public string Email { get; set; }
        //==============================================================================

        //==============================================================================
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Creación")]
        [Required(ErrorMessage = "El nombre es Obligatorio")]
        public DateTime FechaCreacion { get; set; }
        //==============================================================================

    }
}

Models/ErrorViewModel.cs
namespace CrudASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/InicioController.cs
using CrudASP.Datos;
using CrudASP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using System.Diagnostics;

namespace CrudASP.Controllers
{
    public class InicioController : Controller
    {
        private readonly ApplicationDbContext _contexto;// se llama para poder acceder

        public InicioController(ApplicationDbContext contexto)
        {// aplicamos la inyeccion de dependencias y por medio de la variable contexto podemos aceder a cualquier propiedad
            // o modelo que contenga el programa.
            _contexto = contexto;  
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // utilizamos Entity Framework pora poder acceder a la entidad
            return View(await _contexto.Contactos.ToListAsync()); // retornara una lista 
        }

        [HttpGet]
        public async Task<IActionResult> Crear()// si no existe la vista clieck derecho, agregar vista >= vista reizor vacia, crear y nombre igual al metodo
        {
            // utilizamos Entity Framework pora poder acceder a la entidad
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]// Impide ataques Xcsc
        public async Task<IActionResult> Crear(Contacto contacto)
        {
            // cuando el modelo tiene datos osea que las validaciones se cumplen
            if (ModelState.IsValid)
            {
                // se envian los datos
                _contexto.Contactos.Add(contacto);
                contacto.FechaCreacion = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd"));
                await _contexto.SaveChangesAsync(); // se realiza el guardado 
                return RedirectToAction(nameof(Index));// y retorna la vista
            }
            // si no tiene datos retorna la vista
            return View();
        }

        // metodo para editar validamos que el id que buscamos no venga vacio
        [HttpGet]
        public IActionResult Editar(int? id) 
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacto = _contexto.Contactos.Find(id);

            if (contacto == null)
            {
                return NotFound();
            }
            return View(contacto);
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]// Impide ataques Xcsc
        public async Task<IActionResult> Editar(Contacto contacto)
        {
            // cuando el modelo tiene datos osea que las validaciones se cumplen
            if (ModelState.IsValid)
            {
                // se envian los datos
                _contexto.Update(contacto);
                contacto.FechaCreacion = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd"));
                await _contexto.SaveChangesAsync(); // se realiza el guardado 
                return RedirectToAction(nameof(Index));// y retorna la vista
            }
            // si no tiene datos retorna la vista
            return View();
        }

        [HttpGet]
       public IActionResult Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var contacto = _contexto.Contactos.Find(id);

            if (contacto == null)
            {
                return NotFound();
            }
            return View(contacto);
        }


        [HttpGet]
        public IActionResult Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var contacto = _contexto.Contactos.Find(id);

            if (contacto == null)
            {
                return NotFound();
            }
            return View(contacto);
        }

        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]// Impide ataques Xcsc
        public async Task<IActionResult> EliminarContacto(int? id)
        {
            var contacto = await _contexto.Contactos.FindAsync(id);
            if (contacto == null)
            {
                return View();
            }
            // borramos el contacto
            _contexto.Contactos.Remove(contacto);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }








        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Inicio/Crear.cshtml
@model CrudASP.Models.Contacto

@{
    ViewData["Title"] = "Crear Contacto";
}
<link rel="stylesheet" href="~/css/EstilosPersonalizados.css" asp-append-version="true" />

<div class="container Espacio">
    <img class=" col-4  CardBodyPersonalizada ImagenP" src="https://cdn-icons-png.flaticon.com/512/1802/1802667.png" alt="Logo">
    <div class="text-center">
        <h1 class="text-center">Contactos en INA Upala ASP.Net Core 7</h1>
    </div>
</div>

<div class="row " style="padding-left:20px;">
    <div class="offser-12  BorderRadios">
        <div class="card border CardBodyPersonalizada">
            <div class="card-header cardHeaderPersonalisada">
                <h3 class="textocolor">
                    <strong>
                        Crear Contacto
                    </strong>
                </h3>

            </div>
            <div class="card-body bodyAgenda2">
               <form asp-action="Crear" method="post">
                   <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group forms">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-circle Separacion" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
                        <label asp-for="Nombre" class="control-label Labelmodal"></label>
                       <input  asp-for="Nombre" class="form-control" placeholder="Ingresa el Nombre"/>
                       <span  asp-validation-for="Nombre" class="text-danger"></span>
                   </div>

                    <div class="form-group forms">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-telephone-fill Separacion" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                        </svg>
                        <label asp-for="Telefono" class="control-label Labelmodal"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group forms">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-envelope-paper-fill Separacion" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M6.5 9.5 3 7.5v-6A1.5 1.5 0 0 1 4.5 0h7A1.5 1.5 0 0 1 13 1.5v6l-3.5 2L8 8.75l-1.5.75ZM1.059 3.635 2 3.133v3.753L0 5.713V5.4a2 2 0 0 1 1.059-1.765ZM16 5.713l-2 1.173V3.133l.941.502A2 2 0 0 1 16 5.4v.313Zm0 1.16-5.693 3.337L16 13.372v-6.5Zm-8 3.199 7.941 4.412A2 2 0 0 1 14 16H2a2 2 0 0 1-1.941-1.516L8 10.072Zm-8 3.3 5.693-3.162L0 6.873v6.5Z" />
                        </svg>
                        <label asp-for="Celular" class="control-label Labelmodal"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingresa el Celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group forms">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-calendar2-week-fill Separacion" viewBox="0 0 16 16">
                            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zm9.954 3H2.545c-.3 0-.545.224-.545.5v1c0 .276.244.5.545.5h10.91c.3 0 .545-.224.545-.5v-1c0-.276-.244-.5-.546-.5zM8.5 7a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm3 0a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM3 10.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z" />
                        </svg>
                        <label asp-for="Email" class="control-label Labelmodal"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="BorderTop modal-footers">
                            <a style="border-radius: 10px" type="button" class="btn btn-outline-danger d-block mx-auto"  asp-action="Index" asp-controller="Inicio">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-reply-all-fill" viewBox="0 0 16 16">
                                <path d="M8.021 11.9 3.453 8.62a.719.719 0 0 1 0-1.238L8.021 4.1a.716.716 0 0 1 1.079.619V6c1.5 0 6 0 7 8-2.5-4.5-7-4-7-4v1.281c0 .56-.606.898-1.079.62z" />
                                <path d="M5.232 4.293a.5.5 0 0 1-.106.7L1.114 7.945a.5.5 0 0 1-.042.028.147.147 0 0 0 0 .252.503.503 0 0 1 .042.028l4.012 2.954a.5.5 0 1 1-.593.805L.539 9.073a1.147 1.147 0 0 1 0-1.946l3.994-2.94a.5.5 0 0 1 .699.106z" />
                            </svg>
                            Volver
                        </a>
                        <button type="submit" class=" btn btn-outline-info d-block mx-auto">
                            <svg style="margin-right: 5px;" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                                <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
                            </svg>
                            Crear Usuario
                        </button>
                    </div>
               </form>
            </div>
        </div>
    </div>
</div>

Views/Inicio/Detalle.cshtml
@model CrudASP.Models.Contacto

@{
    ViewData["Title"] = "Detalles Contacto";
}



<div class="text-center">
    <Image class="offser-9 col-3 mb-3" style="width:100px; height:100px" src="https://play-lh.googleusercontent.com/kyA7O0EaQqSDdnlB6-OkUkfHOn2t6YxOkO1cT9W5cdOQVxva9e6l85rhJ5Au5Ugzd9o"></Image>
    <h1 class="text-center">Contactos INA Upala ASP.Net Core 7</h1>
</div>

<div class="row">
    <div class="offser-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        Detalles del Contacto
                    </strong>
                </h3>

            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombre: </strong>@Html.DisplayFor(m => m.Nombre)</li>
                    <li class="list-group-item"><strong>Telefono: </strong>@Html.DisplayFor(m => m.Telefono)</li>
                    <li class="list-group-item"><strong>Celular: </strong>@Html.DisplayFor(m => m.Celular)</li>
                    <li class="list-group-item"><strong>Email: </strong>@Html.DisplayFor(m => m.Email)</li>
                    <li class="list-group-item"><strong>Fecha Creación: </strong>@Html.DisplayFor(m => m.FechaCreacion)</li>

                </ul>
 
                <a style="border-radius: 10px; margin-top:10px" class="btn btn-outline-primary btn-sm" asp-action="Index" asp-controller="Inicio">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-reply-all-fill" viewBox="0 0 16 16">
                        <path d="M8.021 11.9 3.453 8.62a.719.719 0 0 1 0-1.238L8.021 4.1a.716.716 0 0 1 1.079.619V6c1.5 0 6 0 7 8-2.5-4.5-7-4-7-4v1.281c0 .56-.606.898-1.079.62z" />
                        <path d="M5.232 4.293a.5.5 0 0 1-.106.7L1.114 7.945a.5.5 0 0 1-.042.028.147.147 0 0 0 0 .252.503.503 0 0 1 .042.028l4.012 2.954a.5.5 0 1 1-.593.805L.539 9.073a1.147 1.147 0 0 1 0-1.946l3.994-2.94a.5.5 0 0 1 .699.106z" />
                    </svg>
                    Regresar
                </a>
            </div>
        </div>
    </div>
</div>

Views/Inicio/Editar.cshtml
@model CrudASP.Models.Contacto

@{
    ViewData["Title"] = "Editar Contacto";
}

<div class="text-center">
    <Image class="offser-9 col-3 mb-3" style="width:100px; height:100px" src="https://play-lh.googleusercontent.com/kyA7O0EaQqSDdnlB6-OkUkfHOn2t6YxOkO1cT9W5cdOQVxva9e6l85rhJ5Au5Ugzd9o"></Image>
    <h1 class="text-center">Contactos INA Upala ASP.Net Core 7</h1>
</div>

<div class="row">
    <div class="offser-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        Editar Contacto
                    </strong>
                </h3>

            </div>
            <div class="card-body">
                <form asp-action="Editar">

                    @* Enviamos el ID de manera Oculta *@

                    <input type="hidden" asp-for="Id" />

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el Nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingresa el Celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-3">
                        <button type="submit" class=" btn btn-outline-info d-block mx-auto">
                            <svg style="margin-right: 5px" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                            </svg>
                              Editar Usuario
                        </button>
                    </div>
                </form>
                <a asp-action="Index" asp-controller="Inicio"> Regresar</a>
            </div>
        </div>
    </div>
</div>

Views/Inicio/Eliminar.cshtml
@model CrudASP.Models.Contacto

@{
    ViewData["Title"] = "Eliminar Contacto";
}

<div class="text-center">
    <Image class="offser-9 col-3 mb-3" style="width:100px; height:100px" src="https://play-lh.googleusercontent.com/kyA7O0EaQqSDdnlB6-OkUkfHOn2t6YxOkO1cT9W5cdOQVxva9e6l85rhJ5Au5Ugzd9o"></Image>
    <h1 class="text-center">Contactos INA Upala ASP.Net Core 7</h1>
</div>

<div class="row">
    <div class="offser-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        Eliminar Contacto
                    </strong>
                </h3>

            </div>
            <div class="card-body">
                <form asp-action="Eliminar">

                    @* Enviamos el ID de manera Oculta *@

                    <input type="hidden" asp-for="Id" />

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el Nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingresa el Celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-3">
                        <button style="border-radius: 10px" type="submit" class=" btn btn-outline-danger d-block mx-auto">
                            <svg style="margin-right: 5px;  xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-fill-x" viewBox="0 0 16 16">
                                <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-9 8c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z" />
                                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm-.646-4.854.646.647.646-.647a.5.5 0 0 1 .708.708l-.647.646.647.646a.5.5 0 0 1-.708.708l-.646-.647-.646.647a.5.5 0 0 1-.708-.708l.647-.646-.647-.646a.5.5 0 0 1 .708-.708Z" />
                            </svg>
                            Eliminar Usuario
                        </button>
                    </div>
                </form>
                <a asp-action="Index" asp-controller="Inicio"> Regresar</a>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudASPCore7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudASP.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"/>
</head>
<body>
    <header class="headers">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  box-shadow mb-3 Colornarvar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Inicio" asp-action="Index">CrudASPCore7</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container ">
        <main role="main" class="pb-3 main">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted box-shadow ">
        <div class="container-fluid ">
            &copy; 2023 - CrudASPCore7
            @*- <a asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>